name: SimpMC-BW1.8.8
version: ${project.version}
authors: [andrei1058, Minecraft0122]
description: 兼容 Spigot 1.8.8 和 1.8.9 的起床战争插件
main: com.andrei1058.bedwars.BedWars
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,PartyAndFriends,Spigot-Party-API-PAF]
#load: STARTUP
