name: BedWars1058
api-version: '1.21'
version: ${project.version}
author: andrei1058
description: BedWars minigame by andrei1058
main: com.andrei1058.bedwars.BedWars
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,VipFeatures,PartyAndFriends,Spigot-Party-API-PAF]
#load: STARTUP
